#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Joy
from geometry_msgs.msg import Twist

class IMRTTeleop:

    def __init__(self):
        self._cmd_pub = rospy.Publisher('teleop/cmd_vel', Twist, queue_size=1)
        rospy.Subscriber('joy', Joy, self._joy_callback)
        self._vx_gain = 0.7
        self._wz_gain = 0.9

    def _joy_callback(self, joy_msg):
        vx = joy_msg.axes[0] * self._vx_gain
        wz = -joy_msg.axes[3] * self._wz_gain

        twist_msg = Twist()
        twist_msg.linear.x = vx
        twist_msg.angular.z = wz
        self._cmd_pub.publish(twist_msg)


if __name__ == '__main__':
    rospy.init_node('imrt_teleop')
    IMRTTeleop()
    rospy.spin()
